apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: flask-devops-platform
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/gsmohamedfarooq/flask-devops-platform-gitops.git
    targetRevision: main
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: flask-devops-platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
