apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-devops-platform
  labels:
    app: flask-devops-platform

spec:
  replicas: 3

  selector:
    matchLabels:
      app: flask-devops-platform

  template:
    metadata:
      labels:
        app: flask-devops-platform

    spec:
      containers:
        - name: flask
          image: ghcr.io/gsmohamedfarooq/flask-devops-platform:361fc23bf0a98f8bc4c5fdc254bf425a0d90cee1
          ports:
            - containerPort: 5000
