apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-devops-platform
  labels:
    app: flask-devops-platform

spec:
  replicas: 3
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
      
  selector:
    matchLabels:
      app: flask-devops-platform

  template:
    metadata:
      labels:
        app: flask-devops-platform

    spec:
      containers:
        - name: flask
          image: ghcr.io/gsmohamedfarooq/flask-devops-platform:f4195cd2eba10b550d3cb459fbe735fdf2a77265
          ports:
            - containerPort: 5000
