apiVersion: v1
kind: Service
metadata:
  name: flask-devops-platform
  labels:
    app: flask-devops-platform

spec:
  selector:
    app: flask-devops-platform

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: ClusterIP
